[theme]
primaryColor = "#10b981"
backgroundColor = "#18181B"
secondaryBackgroundColor = "#242427"
textColor = "#E2E8F0"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
enableStaticServing = false

[browser]
gatherUsageStats = false
